name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Java 21 をセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Maven でビルドとテスト
        run: mvn -B clean install

      - name: AWS CLI の設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-1'

      - name: Lambda 用の JAR パッケージを作成
        run: mvn clean package -DskipTests

      - name: Lambda 関数にデプロイ
        run: |
          aws lambda update-function-code --function-name StudyAppFunction --zip-file fileb://target/study-app.jar