name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # ← または deploy 対象のブランチ名に変更

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Upload to AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Update Lambda function code
        run: |
            aws lambda update-function-code \
            --function-name StudyAppFunction \
            --zip-file fileb://target/study-app.jar
